### ISSUE TITLE
[BUG] Error loading profile

### ISSUE THREAD

**Issue by Imikeeee** [austinhuang0131/instagrabber#89] opened 2020-08-27 23:12 UTC
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

After login it didnt load anything and I got tge error message : error loading profile

## Steps

DETAILED Steps
Right down corner gear icon , click
Login button click
Login with the form
Error and white screen

## Environment

 - Device: lenovo tab3 10
 - Android version: 6

## Additional info
[4_5926909896153892549.zip](https://github.com/austinhuang0131/instagrabber/files/5139118/4_5926909896153892549.zip)

**Comment by Imikeeee** [comment] 2020-08-27 23:14
I cant see the steps in the post 

## Steps

**Comment by austinhuang0131** [comment] 2020-08-27 23:35
duplicate #76

**Comment by austinhuang0131** [comment] 2020-08-29 19:36
Duplicate of #76

**Closed** 2020-09-01 17:37 UTC
Labels: bug, compatibility, duplicate

**Comment by austinhuang0131** [comment] 2020-09-02 01:52
Added in v18.2
